apiVersion: v1
kind: Secret
metadata:
  name: ctfd-secret
  namespace: ctfd
type: Opaque
stringData:
  secret-key: "ctfd-dev-secret-change-in-prod"
  database-url: "mysql+pymysql://ctfd:ctfd-secret@ctfd-db:3306/ctfd"
  redis-url: "redis://keydb:6379"
